### PR TITLE
refactor!: change subprojects to modules

### PR DESCRIPTION
**Pull request by asterwyx**
BEARKING_CHANGE: Change subprojects framework to modules framework. Add more modern style cmake.

Log: chang subprojects to modules

### CODE REVIEW

**Review by Groveer — COMMENTED** [review]
+1

**Review by 18202781743 — DISMISSED** [review]

**Review by xzl01 — COMMENTED** [review]
+1

**Comment by kegechen** [comment]
qmake cmake pkgconfig的方式分别测试一下是否能正常找到头文件，链接成功

**Review by kegechen — APPROVED** [review]

**Review by uniontechzhangsong — COMMENTED** [review]
+1

**Pull request merged**
