### PR TITLE
fix: Fix some warnings

### PR DESCRIPTION
**Pull request by asterwyx**
Fix a logic error, a control flow reach end warning and a sign-compare warning. Remove useless configure statement.

Log: clean cmake and warnings.

### CODE REVIEW

**Review by Groveer — COMMENTED** [review]
/+1

**Comment by xzl01** [comment]
+1

**Comment by uniontechzhangsong** [comment]
+1

**Comment by toberyan** [comment]
+1

**Review by xzl01 — APPROVED** [review]

**Pull request merged**
